### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by andreped** [jpdefrutosSINTEF/dicom_anonymizer#1]
After installing the program on Ubuntu, the icon(s) are not showing.

Generated binaries can be found [here](https://github.com/jpdefrutosSINTEF/dicom_anonymizer/actions) for further debugging.

**Comment by jpdefrutos** [comment]
Thanks! The path was wrong:
`---QIcon path: /usr/local/bin/DICOMAnonymizer/dicomanonymizer/../images/up.png`

**Comment by andreped** [comment]
Great! Assuming that his is solved, I am closing this comment.

**Comment by jpdefrutos** [comment]
If an element in the path is missing from the system, Linux cannot find the path.
`os.path.split(os.path.dirname(os.path.realpath(__file__)))` includes the directory "dicomanonymizer" which is not present in the install dir. Hence it fails.

See commits d771b96a9eb0035f215add3b0c352285c1abeefd and 4224c0d363cb0faf3e1c4a42ff0e374f5b9bc771
